import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { instrumentRegistry } from '../data/instruments/registry';
import { catalogStatusLabel } from '../data/instruments/statusLabels';
import { loadAdminDashboard, reviewPsychologistApplication, setStaffPermissions, type AdminDashboard, type AdminDecision } from '../lib/admin';

type AdminTab = 'summary' | 'users' | 'pending' | 'staff' | 'instruments' | 'projects' | 'reviews' | 'changes' | 'licenses' | 'accesses' | 'publications' | 'audit';
const tabs: Array<{ id: AdminTab; label: string }> = [
  { id: 'summary', label: 'Resumen' }, { id: 'users', label: 'Usuarios' }, { id: 'pending', label: 'Psicólogos pendientes' }, { id: 'staff', label: 'Staff y revisores' }, { id: 'instruments', label: 'Instrumentos' }, { id: 'projects', label: 'Proyectos' }, { id: 'reviews', label: 'Revisiones' }, { id: 'changes', label: 'Solicitudes de cambios' }, { id: 'licenses', label: 'Licencias' }, { id: 'accesses', label: 'Accesos privados' }, { id: 'publications', label: 'Publicaciones' }, { id: 'audit', label: 'Auditoría' },
];
const value = (input: unknown) => input === null || input === undefined ? '—' : Array.isArray(input) ? input.join(', ') : typeof input === 'object' ? JSON.stringify(input) : String(input);

export function AdminPage() {
  const { isOwner } = useAuth(); const [dashboard, setDashboard] = useState<AdminDashboard>(); const [tab, setTab] = useState<AdminTab>('summary'); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function refresh() { setLoading(true); setMessage(''); try { setDashboard(await loadAdminDashboard()); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'No se pudo cargar el panel administrativo.'); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); }, []);
  async function decide(uid: string, decision: AdminDecision) { const note = window.prompt(decision === 'approved' ? 'Nota opcional de aprobación' : 'Indica la razón para la persona solicitante') ?? ''; if (decision !== 'approved' && !note.trim()) { setMessage('La devolución o rechazo requiere una nota.'); return; } try { await reviewPsychologistApplication(uid, decision, note); setMessage('Solicitud actualizada.'); await refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'No se pudo actualizar la solicitud.'); } }
  async function toggleStaff(uid: string, field: 'admin' | 'professionalReviewer', enabled: boolean) { if (!isOwner) { setMessage('Sólo un owner puede modificar el staff.'); return; } try { await setStaffPermissions({ uid, [field]: enabled, active: true, notes: 'Actualizado desde el panel administrativo.' }); setMessage('Permiso actualizado; la persona debe renovar su token.'); await refresh(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'No se pudo actualizar el staff.'); } }
  const cards = useMemo<Array<[string, number]>>(() => dashboard ? [['Usuarios', dashboard.summary.users], ['Pendientes', dashboard.summary.pendingPsychologists], ['Staff', dashboard.summary.reviewers], ['Proyectos', dashboard.summary.projects], ['Cambios', dashboard.summary.changeRequests], ['Publicaciones', dashboard.summary.publications], ['Revisiones', dashboard.summary.clinicalReviews], ['Licencias', dashboard.summary.licenses]] : [], [dashboard]);
  return <section className="stack admin-page"><div className="page-heading"><div><span className="eyebrow">Área protegida</span><h1>Administración</h1><p>Las acciones sensibles pasan por Cloud Functions con claims, correo verificado, App Check y auditoría.</p></div><button className="secondary" onClick={() => void refresh()} disabled={loading}>Actualizar</button></div><nav className="admin-tabs" aria-label="Secciones de administración">{tabs.map((item) => <button className={tab === item.id ? 'active' : 'secondary'} key={item.id} onClick={() => setTab(item.id)} aria-current={tab === item.id ? 'page' : undefined}>{item.label}</button>)}</nav>{message ? <p className="error" role="status">{message}</p> : null}{loading ? <p className="status">Cargando datos administrativos…</p> : null}{!loading && dashboard ? <AdminSection tab={tab} dashboard={dashboard} cards={cards} isOwner={isOwner} onDecision={decide} onStaff={toggleStaff} /> : null}</section>;
}

function AdminSection({ tab, dashboard, cards, isOwner, onDecision, onStaff }: { tab: AdminTab; dashboard: AdminDashboard; cards: Array<[string, number]>; isOwner: boolean; onDecision: (uid: string, decision: AdminDecision) => Promise<void>; onStaff: (uid: string, field: 'admin' | 'professionalReviewer', enabled: boolean) => Promise<void> }) {
  if (tab === 'summary') return <div className="grid admin-summary">{cards.map(([label, count]) => <article className="card" key={label}><span className="eyebrow">{label}</span><strong className="admin-count">{count}</strong></article>)}</div>;
  if (tab === 'users') return <DataTable rows={dashboard.users} columns={['uid', 'name', 'email', 'role', 'createdAt']} empty="No hay usuarios para mostrar." />;
  if (tab === 'pending') return <div className="stack">{dashboard.psychologistsPending.length === 0 ? <Empty text="No hay psicólogos pendientes." /> : dashboard.psychologistsPending.map((person) => <article className="card" key={person.uid}><div className="row-between"><div><h2>{person.name || person.uid}</h2><p>{person.email}</p><p className="muted">{person.professional?.approvalStatus ?? 'pending'} · {(person.professional?.specialties ?? []).join(', ') || 'sin especialidades'}</p></div><div className="row-gap"><button onClick={() => void onDecision(person.uid, 'approved')}>Aprobar</button><button className="secondary" onClick={() => void onDecision(person.uid, 'changes_requested')}>Devolver</button><button className="danger" onClick={() => void onDecision(person.uid, 'rejected')}>Rechazar</button></div></div></article>)}</div>;
  if (tab === 'staff') return <div className="stack">{dashboard.reviewers.map((reviewer) => <article className="card" key={reviewer.uid}><div className="row-between"><div><h2>{reviewer.displayName || reviewer.email || reviewer.uid}</h2><p>{reviewer.email} · correo {reviewer.emailVerified ? 'verificado' : 'sin verificar'}</p><p className="muted">{Object.entries(reviewer.claims).filter(([, enabled]) => enabled).map(([claim]) => claim).join(', ') || 'sin permisos'}</p></div>{isOwner ? <div className="row-gap"><button className="secondary" onClick={() => void onStaff(reviewer.uid, 'admin', !reviewer.claims.admin)}>{reviewer.claims.admin ? 'Quitar admin' : 'Dar admin'}</button><button className="secondary" onClick={() => void onStaff(reviewer.uid, 'professionalReviewer', !reviewer.claims.professional_reviewer)}>{reviewer.claims.professional_reviewer ? 'Quitar reviewer' : 'Dar reviewer'}</button></div> : null}</div></article>)}</div>;
  if (tab === 'instruments') return <DataTable rows={instrumentRegistry.map((instrument) => ({ id: instrument.id, instrumento: instrument.abbreviation, categoría: instrument.subcategory, licencia: catalogStatusLabel(instrument.licenseStatus), técnico: catalogStatusLabel(instrument.scoringStatus), clínico: catalogStatusLabel(instrument.clinicalReviewStatus), acceso: catalogStatusLabel(instrument.accessMode) }))} columns={['instrumento', 'categoría', 'licencia', 'técnico', 'clínico', 'acceso']} empty="No hay instrumentos." />;
  if (tab === 'projects') return <DataTable rows={dashboard.projects} columns={['id', 'title', 'originType', 'status', 'ownerId', 'licenseStatus']} empty="No hay proyectos de instrumentos." />;
  if (tab === 'reviews') return <DataTable rows={dashboard.clinicalReviews} columns={['id', 'instrumentId', 'status', 'reviewerId', 'updatedAt']} empty="No hay revisiones." />;
  if (tab === 'changes') return <DataTable rows={dashboard.changeRequests} columns={['id', 'status', 'authorId', 'reason', 'updatedAt']} empty="No hay solicitudes de cambios." />;
  if (tab === 'licenses') return <DataTable rows={dashboard.licenses} columns={['id', 'status', 'updatedAt', 'expiresAt']} empty="No hay licencias registradas." />;
  if (tab === 'accesses') return <DataTable rows={dashboard.privateAccesses} columns={['id', 'instrumentId', 'reviewerId', 'expiresAt']} empty="No hay accesos privados registrados." />;
  if (tab === 'publications') return <DataTable rows={dashboard.publications} columns={['id', 'version', 'status', 'publishedBy', 'publishedAt', 'checksum']} empty="No hay publicaciones." />;
  return <DataTable rows={dashboard.audit} columns={['id', 'action', 'resourceType', 'resourceId', 'actorId', 'timestamp', 'accessedAt']} empty="No hay eventos de auditoría." />;
}
function DataTable({ rows, columns, empty }: { rows: Array<Record<string, unknown>>; columns: string[]; empty: string }) { if (!rows.length) return <Empty text={empty} />; return <div className="panel table-scroll"><table className="catalog-status-table"><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={String(row.id ?? row.uid ?? index)}>{columns.map((column) => <td key={column}>{value(row[column])}</td>)}</tr>)}</tbody></table></div>; }
function Empty({ text }: { text: string }) { return <div className="empty-state panel"><h2>Sin resultados</h2><p>{text}</p></div>; }
